const [
	defaultJSConfig,
	defaultModuleConfig,
] = require( '@wordpress/scripts/config/webpack.config' );
const {
	requestToExternal,
	requestToHandle,
	requestToExternalModule,
	getFile,
	getWebPackAlias,
} = require( './bin/webpack-helpers' );
// const WooCommerceDependencyExtractionWebpackPlugin = require( '@woocommerce/dependency-extraction-webpack-plugin' );
const DependencyExtractionWebpackPlugin = require( '@wordpress/dependency-extraction-webpack-plugin' );
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const { basename, dirname, resolve } = require( 'path' );

const scriptConfig = {
	...defaultJSConfig,
	entry: {
		// ...defaultJSConfig.entry(),
		// 'editor-scripts': getFile( 'editor-scripts.js' ),
		backend: getFile('backend/index.js'),
        // frontend: getFile('frontend/index.js'),
	},
    output: {
        path: resolve( process.cwd(), 'includes/assets/build' ),
    },
	resolve: {
		...defaultJSConfig.resolve,
		alias: {
			...defaultJSConfig.resolve.alias,
			...getWebPackAlias(),
		},
	},

	plugins: [
		// ...defaultJSConfig.plugins,
		...defaultJSConfig.plugins.filter(
			( plugin ) =>
				plugin.constructor.name !== 'DependencyExtractionWebpackPlugin'
		),
		new DependencyExtractionWebpackPlugin( {
			requestToExternal,
			requestToHandle,
			requestToExternalModule,
		} ),

		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin( {
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		} ),
	],
	/*optimization: {
		splitChunks: {
			chunks: 'all',
			minSize: 1,
			name: 'common',
		},
		// runtimeChunk: { name: 'utils' },
	},*/
};

const moduleConfig = {
	...defaultModuleConfig,
	experiments: { outputModule: true },
	entry: {
		...defaultModuleConfig.entry(),
		// backend: getFile('backend/index.js'),
        // frontend: getFile('frontend/index.js'),
	},
	resolve: {
		...defaultModuleConfig.resolve,
		alias: {
			...defaultModuleConfig.resolve.alias,
			...getWebPackAlias(),
		},
	},

	plugins: [
		// ...defaultModuleConfig.plugins,
		...defaultModuleConfig.plugins.filter(
			( plugin ) =>
				plugin.constructor.name !== 'DependencyExtractionWebpackPlugin'
		),
		new DependencyExtractionWebpackPlugin( {
			requestToExternal,
			requestToHandle,
			requestToExternalModule,
		} ),

		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin( {
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		} ),
	],
};

module.exports = [ scriptConfig, moduleConfig ];